//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WindowsProject1.rc

#define IDS_APP_TITLE 103

#define IDR_MAINFRAME 128
#define IDD_WINDOWSPROJECT1_DIALOG 102
#define IDD_ABOUTBOX 103
#define IDM_ABOUT 104
#define IDM_EXIT 105
#define IDI_WINDOWSPROJECT1 107
#define IDI_SMALL 108
#define IDC_WINDOWSPROJECT1 109
#define IDC_MYICON 2
#ifndef IDC_STATIC
#define IDC_STATIC -1
#define IDS_LOWINK_TITLE 617
#define IDS_LOWINK_TEXT 618
#endif

// APP Controls

#define MAX_LOADSTRING 100
#define IDB_BUT 1001

// Buttons and label IDs
#define RUN_VIDEO_DETECTION_BATCH 208
#define RUN_VOICE_DETECTION 209
#define RUN_VIDEO_DETECTION 210
#define AUTO_LAUNCH_AUDIO_VIDEO 211
#define STOP_DETECTION 070
#define END_VIDEO_DETECTION 073
#define STOP_VOICE_DETECTION 071
#define END_VOICE_DETECTION 072
#define PROC_LABEL 060
#define START_VIDEO_DETECTION_HOMESCREEN 036
#define START_VIDEO_DETECTION_BACKGROUND_HOMESCREEN 037
#define PREPARE_VIDEO_DETECTION_BACKGROUND 040
#define START_VOICE_DETECTION_HOMESCREEN 041
#define START_VOICE_DETECTION_UI 042
#define START_VOICE_DETECTION_BACKGROUND_HOMESCREEN 043
#define PREPARE_VOICE_DETECTION_BACKGROUND 044
#define VOICE_RESULT_LABEL_FAKE 204
#define VOICE_RESULT_LABEL_REAL 205
#define VOICE_RESULT_LABEL_ANALYZING 210
#define VOICE_RESULT_LABEL_INVALID 207

// Notification ID's
#define IDI_NOTIFICATION_TRAY 047
#define MY_TRAY_ICON_MESSAGE WM_USER + 2
#define TOAST_NOTIFICATION_ID WM_USER + 7
#define VISION_RESULT_ID 940
#define VOICE_RESULT_ID 941
#define VOICE_RESULT_UI_RENDER_ID 850

// System Tray ID's
#define TRAY_MENU_OPEN 602
#define TRAY_MENU_WEB_SURF_MODE_VIDEO_RUN 603
#define TRAY_MENU_VIDEO_MODE_VIDEO_RUN 604
#define TRAY_MENU_VIDEO_MODE_VOICE_RUN 605
#define TRAY_MENU_WEB_SURF_MODE_VOICE_RUN 606
#define TRAY_MENU_WEB_SURF_MODE_SIMULTANEOUS_RUN 608
#define TRAY_MENU_VIDEO_MODE_SIMULTANEOUS_RUN 609
#define TRAY_MENU_EXIT 607
#define TRAY_MENU_BACKGROUND_RUN_DISABLE 702
#define TRAY_MENU_CHECKBOX_AUTO_LAUNCH 703
#define TRAY_MENU_LICENSE_KEY_DIALOG 704
#define LICENSE_KEY_SAVE 705
#define LICENSE_KEY_CANCEL 706
#define TRAY_MENU_RESULTS_DIR 707

// GIF animation
#define IDI_WAVEFORM_GIF 111
#define GIF_WAVEFORM_ANIMATION_TIMER_ID 321
#define IDI_LOADING_GIF 322
#define GIF_LOADING_ANIMATION_TIMER_ID 323

// UI Dark mode
#define APP_NAME_TEXT_ID 620
#define IDI_HOMESCREEN_LOGO 621
#define MODEL_MODE_DROPDOWN 623
#define IDB_VIDEO_MODEL 624
#define IDB_GENERIC_MODEL 625
#define MODEL_MODE_DROPDOWN_LABEL 626
#define VOICE_HS_PANEL_LABEL 627
#define DEMO_SETTINGS_HS_PANEL_LABEL 652
#define DEMO_SETTINGS_HS_DURATION_LABEL 653
#define DEMO_SETTINGS_HS_DURATION_TEXT_FIELD 654
#define VISION_HS_PANEL_BOX 628
#define VOICE_HS_PANEL_BOX 629
#define VISION_HS_PANEL_LABEL 630
#define VISION_UI_RESULT_RENDER 631
#define VISION_RESULT_FLASH 632
#define RESULT_BUTTON_BOX_REAL 633
#define RESULT_BUTTON_BOX_FAKE 634
#define VISION_UI_RESULT_TIMER_ID 635
#define VOICE_CONTAINER_BUTTON_BOX 636
#define DEMO_SETTINGS_HS_PANEL_BOX 637
#define HEARTBEAT_TIMER 638
#define AUTO_LAUNCH_TIMER 639
#define RESET_PID_TIMER 640

// UI changes for Media Release
#define VISION_RESULT_TABLE 641
#define VISION_DETECTION_UPDATE 642
#define RESULT_TABLE_FRAME_COL 643
#define RESULT_TABLE_FACE_COL 644
#define RESULT_TABLE_REAL_COL 645
#define RESULT_TABLE_FAKE_COL 646
#define RESULT_TABLE_RESULT_COL 647
#define RESULT_TABLE_REAL_IMG 648
#define RESULT_TABLE_FAKE_IMG 649
#define VOICE_GRAPH_RENDER 650
#define VOICE_GRAPH_NEW_SCORE 651

// Velopack update
#define VELOPACK_DOWNLOAD_PROGRESS 652
#define VELOPACK_DOWNLOAD_DONE 653

// EULA status
#define EULA_STATUS_ACCEPTED 655
#define EULA_STATUS_REJECTED 656

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC 130
#define _APS_NEXT_RESOURCE_VALUE 129
#define _APS_NEXT_COMMAND_VALUE 32771
#define _APS_NEXT_CONTROL_VALUE 1000
#define _APS_NEXT_SYMED_VALUE 110
#endif
#endif
